spring:
  application:
      name: Bank


  datasource:
    url: jdbc:postgresql://localhost:5432/bank
    driver-class-name: org.postgresql.Driver
    username: root
    password: 12345


  jpa.show-sql: true
  jpa.hibernate.ddl-auto: update


jwt:
  secret: 984hg493gh0439rtgr0429uruj2309yh937gc763fe87t3f89723gf
  lifetime: 30m